version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_prosperia
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mini_prosperia"]
      interval: 10s
      timeout: 5s
      retries: 5
    # For production, you might not want to expose the port to the host
    # ports:
    #   - "5432:5432"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    # Load environment variables from a .env file in the project root
    env_file:
      - .env
    environment:
      # Overrides .env file variables
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mini_prosperia?schema=public"
      NODE_ENV: production
      PORT: 3000

volumes:
  pgdata:
    # In a real production setup, you might want to use a managed database
    # or have a more robust backup strategy for this volume.
    name: mini_prosperia_prod_data
